# zsh theme
export ZSH="/home/brad/.oh-my-zsh"
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_DISABLE_PROMPT=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX=''
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\ue0bc'
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uf93f'
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=' \uf92f'
POWERLEVEL9K_HOME_ICON=' \ufcd0'
POWERLEVEL9K_HOME_SUB_ICON=' \uf07c'
POWERLEVEL9K_FOLDER_ICON=' \uf07c'
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uf09b'
POWERLEVEL9K_VCS_BRANCH_ICON=''
POWERLEVEL9K_PYTHON_ICON='\ue606'

# functions
function sandbox {
    . ~/sandbox/bin/activate
}

# source
source $ZSH/oh-my-zsh.sh
