-- these general settings must come first
require 'plugins'
require '_keymaps'
require '_settings'

-- functional settings
require '_treesitter'
require '_scrollview'
require '_statusline'
require '_kommentary'
require '_indentline'
require '_telescope'
require '_gitsigns'
require '_startify'
require '_tabline'
require '_lspkind'
require '_compe'
require '_saga'
require '_tree'
require '_lsp'
