-- order is important, ensure plugins, _keymaps & _settings come first
require 'plugins'
require '_keymaps'
require '_settings'
require '_treesitter'
require '_scrollview'
require '_telescope'
require '_gitgutter'
require '_startify'
require '_statusline'
require '_tabline'
require '_lspkind'
require '_compe'
require '_tree'
require '_lsp'
